/**
 * @license
 * Copyright 2025 Amodal Labs, Inc.
 * SPDX-License-Identifier: MIT
 */

/**
 * Generate a docker-compose.yml for local/staging deployment.
 */
export function generateCompose(serviceName: string): string {
  const safeName = serviceName.replace(/[^a-z0-9-]/gi, '-').toLowerCase();
  return `# Docker Compose for amodal runtime
# Generated by: amodal deploy init

services:
  ${safeName}:
    build: .
    ports:
      - "3847:3847"
    env_file:
      - .env.production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3847/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
`;
}
