/**
 * @license
 * Copyright 2025 Amodal Labs, Inc.
 * SPDX-License-Identifier: MIT
 */

/**
 * Generate a production Dockerfile for amodal runtime.
 */
export function generateDockerfile(): string {
  return `# Multi-stage build for amodal runtime
# Generated by: amodal deploy init

# Stage 1: Build
FROM node:20-slim AS builder
WORKDIR /app
COPY package.json pnpm-lock.yaml* package-lock.json* ./
RUN corepack enable && corepack prepare pnpm@latest --activate 2>/dev/null || npm install
COPY . .
RUN if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile; else npm ci; fi

# Stage 2: Production
FROM node:20-slim AS production
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app .
EXPOSE 3847
CMD ["node", "node_modules/@amodalai/runtime/dist/src/index.js"]
`;
}
